export const LIQUIDID_ABI = [
  {"inputs":[{"internalType":"address","name":"_hunosToken","type":"address"},{"internalType":"address","name":"_initialOwner","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},
  {"inputs":[],"name":"EnforcedPause","type":"error"},
  {"inputs":[],"name":"ExpectedPause","type":"error"},
  {"inputs":[{"internalType":"address","name":"owner","type":"address"}],"name":"OwnableInvalidOwner","type":"error"},
  {"inputs":[{"internalType":"address","name":"account","type":"address"}],"name":"OwnableUnauthorizedAccount","type":"error"},
  {"inputs":[],"name":"ReentrancyGuardReentrantCall","type":"error"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"liquidId","type":"uint256"},{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":false,"internalType":"uint256","name":"liquidationValue","type":"uint256"}],"name":"AssetLiquidated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"liquidId","type":"uint256"},{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":true,"internalType":"address","name":"creator","type":"address"},{"indexed":false,"internalType":"enum LiquidID.AssetType","name":"assetType","type":"uint8"},{"indexed":false,"internalType":"uint256","name":"mintPrice","type":"uint256"}],"name":"AssetMinted","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"liquidId","type":"uint256"},{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":false,"internalType":"uint256","name":"payout","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"penalty","type":"uint256"}],"name":"AssetSoldToPool","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"liquidId","type":"uint256"},{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"}],"name":"AssetTransferred","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"totalAmount","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"eligibleHolders","type":"uint256"}],"name":"DividendsDistributed","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"liquidId","type":"uint256"},{"indexed":false,"internalType":"string","name":"imageURI","type":"string"},{"indexed":false,"internalType":"bytes32","name":"imageHash","type":"bytes32"}],"name":"ImageSet","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"account","type":"address"}],"name":"Paused","type":"event"},
  {"anonymous":false,"inputs":[{"components":[{"internalType":"uint256","name":"commonCharacter","type":"uint256"},{"internalType":"uint256","name":"rareCharacter","type":"uint256"},{"internalType":"uint256","name":"commonCar","type":"uint256"},{"internalType":"uint256","name":"rareCar","type":"uint256"},{"internalType":"uint256","name":"realEstate","type":"uint256"}],"indexed":false,"internalType":"struct LiquidID.PricingConfig","name":"newPricing","type":"tuple"}],"name":"PricingUpdated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"token","type":"address"}],"name":"ProjectTokenAdded","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"creator","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"RoyaltyPaid","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"account","type":"address"}],"name":"Unpaused","type":"event"},
  {"inputs":[{"internalType":"address","name":"_creator","type":"address"}],"name":"addAuthorizedCreator","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"_token","type":"address"}],"name":"addSupportedProjectToken","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"assets","outputs":[{"internalType":"uint256","name":"liquidId","type":"uint256"},{"internalType":"address","name":"owner","type":"address"},{"internalType":"address","name":"creator","type":"address"},{"internalType":"string","name":"metadataURI","type":"string"},{"internalType":"enum LiquidID.AssetType","name":"assetType","type":"uint8"},{"internalType":"uint256","name":"mintPrice","type":"uint256"},{"internalType":"uint256","name":"createdAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"},{"internalType":"address","name":"projectToken","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"_owner","type":"address"}],"name":"getOwnerAssets","outputs":[{"internalType":"uint256[]","name":"","type":"uint256[]"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"_liquidId","type":"uint256"}],"name":"getAsset","outputs":[{"components":[{"internalType":"uint256","name":"liquidId","type":"uint256"},{"internalType":"address","name":"owner","type":"address"},{"internalType":"address","name":"creator","type":"address"},{"internalType":"string","name":"metadataURI","type":"string"},{"internalType":"enum LiquidID.AssetType","name":"assetType","type":"uint8"},{"internalType":"uint256","name":"mintPrice","type":"uint256"},{"internalType":"uint256","name":"createdAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"},{"internalType":"address","name":"projectToken","type":"address"}],"internalType":"struct LiquidID.Asset","name":"","type":"tuple"}],"stateMutability":"view","type":"function"}
];

export const LIQUIDID_ADDRESS = "0x5f734217838F3506913d0AD1abd75aA47BfcC6d7"; 